// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKAnLWLpNTQP9vULs1awn79ftzF0BOz0w',
    appId: '1:52957570887:web:5ffc67973ebc1d49fd8e62',
    messagingSenderId: '52957570887',
    projectId: 'bioband01',
    authDomain: 'bioband01.firebaseapp.com',
    storageBucket: 'bioband01.firebasestorage.app',
    measurementId: 'G-R0EZ55H0DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATixYE0s76je-2YLxSk1kkCYBPUmMFOI8',
    appId: '1:52957570887:android:96484fa233fc44f5fd8e62',
    messagingSenderId: '52957570887',
    projectId: 'bioband01',
    storageBucket: 'bioband01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU2ZPbebeQ5IprVlCgSeuAz7whPT4MuF4',
    appId: '1:52957570887:ios:cad6ac6919c878b6fd8e62',
    messagingSenderId: '52957570887',
    projectId: 'bioband01',
    storageBucket: 'bioband01.firebasestorage.app',
    iosBundleId: 'com.example.nadiPariksh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU2ZPbebeQ5IprVlCgSeuAz7whPT4MuF4',
    appId: '1:52957570887:ios:cad6ac6919c878b6fd8e62',
    messagingSenderId: '52957570887',
    projectId: 'bioband01',
    storageBucket: 'bioband01.firebasestorage.app',
    iosBundleId: 'com.example.nadiPariksh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKAnLWLpNTQP9vULs1awn79ftzF0BOz0w',
    appId: '1:52957570887:web:f1801e5216173a60fd8e62',
    messagingSenderId: '52957570887',
    projectId: 'bioband01',
    authDomain: 'bioband01.firebaseapp.com',
    storageBucket: 'bioband01.firebasestorage.app',
    measurementId: 'G-0V3D5DZK6Y',
  );
}
